#!/bin/sh

for ver in 1.4 1.5 1.6 2 2.0 2.1 2.2 2.3 2.4 2.5 2.6 2.7; do
    which python$ver > /dev/null 2>&1 && \
    ( python$ver    test/compile_tests
      python$ver -O test/compile_tests
    )
done
